name: complex-stuff
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10]
    steps:
      - run: "echo ${{ matrix.node }}"
  depend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: "echo job depends on this matrix above"
  depend2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: "echo job depends on this matrix above x2"
  complex:
    needs: [depend, depend2]
    runs-on: ubuntu-latest
    steps:
      - run: "echo complex"
