name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: set deployment as in progress
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://codemonkey51.dev
          environment: production
          initial_status: "in_progress"
      - run: "exit 1"
        name: "Deploy"
      - uses: chrnorm/deployment-action@releases/v1
        if: " ${{ success() }} "
        name: Set Deployment as complete
        id: finish_deployment
        with:
          token: "${{ github.token }}"
          target_url: https://codemonkey51.dev
          environment: production
          initial_status: "success"
      - uses: chrnorm/deployment-action@releases/v1
        if: " ${{ failure() }} "
        name: Set Deployment as fail
        with:
          token: "${{ github.token }}"
          target_url: https://codemonkey51.dev
          environment: production
          initial_status: "failure"
