name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: Test GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://codemonkey51.dev
          environment: production
          initial_status: "success"
