name: matrix-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: [1, 2, 3]
        y: [3, 2, 1]
    steps:
      - run: "echo ${{ matrix.x }}, ${{ matrix.y }}"
        name: "matrix ${{ matrix.x }} ${{ matrix.y }}"
